---

- name: COLLECTD | Installation
  package:
    name: "collectd={{ collectd_version }}*"
    state: present
  notify: Restart collectd

- name: COLLECTD | Configuration
  template:
    src: "etc/collectd/collectd.conf.j2"
    dest: "/etc/collectd/collectd.conf"
    owner: root
    group: root
    mode: 0644
  notify: Restart collectd
